version: '3.4'

services:
  gl2tgnotifier:
    image: gl2tgnotifier
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5060:5060
    volumes:
      - ./config:/config      
